# Generated by Django 2.2.1 on 2019-05-01 11:18

from django.db import migrations, models
import editorjs_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', editorjs_field.fields.EditorJSField()),
            ],
        ),
    ]
